<a href="https://colab.research.google.com/github/qazakhi515/Reja./blob/master/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [1]:
import pandas as pd

In [11]:
data = {
    'cars': ["BMW", "Volvo", "KIA", "Hyundai", "Mazda", "Ford"],
    'counts': [3, 4, 9, 2, 5, 1]
}

df = pd.DataFrame(data)
print(df)

      cars  counts
0      BMW       3
1    Volvo       4
2      KIA       9
3  Hyundai       2
4    Mazda       5
5     Ford       1

In [12]:
df.head()

      cars  counts
0      BMW       3
1    Volvo       4
2      KIA       9
3  Hyundai       2
4    Mazda       5

In [13]:
df.tail(-1)

      cars  counts
1    Volvo       4
2      KIA       9
3  Hyundai       2
4    Mazda       5
5     Ford       1

In [14]:
df.shape

(6, 2)

In [15]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [16]:
df.dtypes

cars      object
counts     int64
dtype: object

In [18]:
df.describe() #std standard deviation bu  bir biriga oxshashlik 0 bolsa hammasi bir xil. % 25 esa 2.25dan kichik yokida 2,25 ga teng.

         counts
count  6.000000
mean   4.000000
std    2.828427
min    1.000000
25%    2.250000
50%    3.500000
75%    4.750000
max    9.000000

In [20]:
df.iloc[2:] #2- dan boahlab hammasini chiqarib beradi

      cars  counts
2      KIA       9
3  Hyundai       2
4    Mazda       5
5     Ford       1

In [24]:
df.loc[2:5, "cars"]

2        KIA
3    Hyundai
4      Mazda
5       Ford
Name: cars, dtype: object

In [25]:
df[df["counts"] >= 3]

    cars  counts
0    BMW       3
1  Volvo       4
2    KIA       9
4  Mazda       5